backend:
  name: github
  repo: carte-data/carte
  branch: main
media_folder: "public/images/uploads"
custom_logo: https://cartedata.com/ligature.svg
public_folder: "/images/uploads"
collections:
  - name: dataset
    label: dataset
    folder: data/datasets
    create: false
    delete: false
    slug: '{{title}}'
    path: '{{connection}}/{{database}}/{{slug}}.md'
    preview_path: 'dataset/{{connection}}/{{database}}/{{title}}'
    view_groups:
      - label: Connection
        field: connection
    fields:
      - label: Title
        name: title
        widget: string
      - label: Connection
        name: connection
        widget: hidden
      - label: Location
        name: location
        widget: string
        required: false
      - label: Description
        name: body
        widget: markdown
        required: false
      - label: Database
        name: database
        widget: hidden
      - label: Columns
        name: columns
        widget: list
        allow_add: false
        summary: '{{fields.name}}'
        collapsed: true
        fields:
          - label: Name
            name: name
            widget: string
          - label: Type
            name: type
            widget: hidden
          - label: Description
            name: description
            widget: text
            required: false
